# Generated by Django 5.0.11 on 2025-01-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tanda_labor', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=20)),
                ('porciento_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentCarApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('no_tarjeta_cr', models.CharField(max_length=50)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tipo_persona', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentCarApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('no_chasis', models.CharField(max_length=50, unique=True)),
                ('no_motor', models.CharField(max_length=50, unique=True)),
                ('no_placa', models.CharField(max_length=50, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.modelo')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.tipocombustible')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RentaDevolucion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_renta', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('monto_por_dia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_ralladuras', models.BooleanField()),
                ('cantidad_combustible', models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Lleno', 'Lleno')], max_length=10)),
                ('tiene_goma_respuesta', models.BooleanField()),
                ('tiene_gato', models.BooleanField()),
                ('tiene_roturas_cristal', models.BooleanField()),
                ('estado_gomas', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.cliente')),
                ('empleado_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.estado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentCarApp.vehiculo')),
            ],
        ),
    ]
