# Generated by Django 5.1.5 on 2025-01-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentCarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
