# Generated by Django 5.1.5 on 2025-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentCarApp', '0002_remove_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='estado_gomas',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_delantera_derecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_delantera_izquierda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_trasera_derecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_trasera_izquierda',
            field=models.BooleanField(default=True),
        ),
    ]
